/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package procurement_order_tracking_system;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Sarvein Rao
 */
public class Purchase_Orders extends javax.swing.JFrame {

    /**
     * Creates new form Purchase_Orders
     */
    public Purchase_Orders() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblPOheading = new javax.swing.JLabel();
        btnHomePO = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPO = new javax.swing.JTable();
        btnVPO = new javax.swing.JButton();
        txtPOS = new javax.swing.JTextField();
        btnPOreset = new javax.swing.JButton();
        btnPOsearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        lblPOheading.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblPOheading.setForeground(new java.awt.Color(0, 0, 0));
        lblPOheading.setText("Purchase Orders");

        btnHomePO.setBackground(new java.awt.Color(102, 102, 255));
        btnHomePO.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnHomePO.setForeground(new java.awt.Color(0, 0, 0));
        btnHomePO.setText("Home");
        btnHomePO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHomePO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
                .addComponent(lblPOheading, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(310, 310, 310))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHomePO)
                    .addComponent(lblPOheading, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tblPO.setBackground(new java.awt.Color(255, 255, 255));
        tblPO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Purchase Order ID", "Estimated Delivery", "Supplier Name", "Supplier Contact", "Payment Terms", "Item ID", "Item Name", "Total", "Order Status"
            }
        ));
        jScrollPane1.setViewportView(tblPO);

        btnVPO.setText("View PO");
        btnVPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVPOActionPerformed(evt);
            }
        });

        btnPOreset.setText("Reset");
        btnPOreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPOresetActionPerformed(evt);
            }
        });

        btnPOsearch.setText("Search");
        btnPOsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPOsearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVPO)
                        .addGap(18, 18, 18)
                        .addComponent(btnPOreset))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtPOS, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnPOsearch)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVPO)
                            .addComponent(btnPOreset))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPOsearch))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomePOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePOActionPerformed
        DashboardSM smd = new DashboardSM();
        smd.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnHomePOActionPerformed

    private void btnVPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVPOActionPerformed
        // Load the purchase orders
        PurchaseOrder po = new PurchaseOrder();
        ArrayList<PurchaseOrder> purchaseOrders = po.loadPurchaseOrder();

        // Define the table model 
        DefaultTableModel model = (DefaultTableModel) tblPO.getModel();
        model.setRowCount(0); // Clear existing rows in the table

        // Add rows to the table model
        for (PurchaseOrder order : purchaseOrders) {
            Object[] row = {
                order.getPurchaseOrderID(),
                order.getEstimatedDelivery(),
                order.getSupplierName(),
                order.getSupplierContact(),
                order.getPaymentTerms(),
                order.getItemID(),
                order.getItemName(),
                order.getTotal(),
                order.getOrderStatus()
            };
            model.addRow(row);
        }
    }//GEN-LAST:event_btnVPOActionPerformed

    private void btnPOsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPOsearchActionPerformed
        // Retrieve input from text fields
        String searchPOID = txtPOS.getText().trim();
        

        // Load the purchase orders
        PurchaseOrder po = new PurchaseOrder();
        ArrayList<PurchaseOrder> purchaseOrders = po.loadPurchaseOrder();

        // Define the table model (assuming you have a JTable named jTablePurchaseOrders)
        DefaultTableModel model = (DefaultTableModel) tblPO.getModel();
        model.setRowCount(0); 

        // Filter and add rows to the table model
        for (PurchaseOrder order : purchaseOrders) {
            boolean matchesPOID = searchPOID.isEmpty() || order.getPurchaseOrderID().equalsIgnoreCase(searchPOID);
            

            if (matchesPOID) {
                Object[] row = {
                    order.getPurchaseOrderID(),
                    order.getEstimatedDelivery(),
                    order.getSupplierName(),
                    order.getSupplierContact(),
                    order.getPaymentTerms(),
                    order.getItemID(),
                    order.getItemName(),
                    order.getTotal(),
                    order.getOrderStatus()
                };
                model.addRow(row);
            }
        }

        // Show a message if no results found
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No results found for the given criteria.");
        }
    }//GEN-LAST:event_btnPOsearchActionPerformed

    private void btnPOresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPOresetActionPerformed
        // Clear the search fields
        txtPOS.setText("");
        

        // Load all purchase orders
        PurchaseOrder po = new PurchaseOrder();
        ArrayList<PurchaseOrder> purchaseOrders = po.loadPurchaseOrder();

        // Define the table model (assuming you have a JTable named jTablePurchaseOrders)
        DefaultTableModel model = (DefaultTableModel) tblPO.getModel();
        model.setRowCount(0); // Clear existing rows in the table

        // Add all purchase orders back to the table model
        for (PurchaseOrder order : purchaseOrders) {
            Object[] row = {
                order.getPurchaseOrderID(),
                order.getEstimatedDelivery(),
                order.getSupplierName(),
                order.getSupplierContact(),
                order.getPaymentTerms(),
                order.getItemID(),
                order.getItemName(),
                order.getTotal(),
                order.getOrderStatus()
            };
            model.addRow(row);
        }

    }//GEN-LAST:event_btnPOresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchase_Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchase_Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchase_Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchase_Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchase_Orders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHomePO;
    private javax.swing.JButton btnPOreset;
    private javax.swing.JButton btnPOsearch;
    private javax.swing.JButton btnVPO;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPOheading;
    private javax.swing.JTable tblPO;
    private javax.swing.JTextField txtPOS;
    // End of variables declaration//GEN-END:variables
}
